### ISSUE TITLE
Mod Not Loading

### ISSUE THREAD

**Issue by kierkat10** [xzxADIxzx/Join-and-kill-em-together#10]
When going into the mods section of UMM, I see all of my other mods (none are activated fyi), and this invisible box that is supposedly the mod instead of it. I can't use it or anything. Also, putting this into my UMM Mods folder makes more than half of the mods in the folder disappear. Please help!
![image](https://github.com/xzxADIxzx/Join-and-kill-em-together/assets/136650292/9dcfceb1-584c-464d-98e2-f1bc96f5c8c1)

**Comment by reddishxgithub** [comment]
did you put the manifest that came with the extracted folder in the UMM mods folder too? It might duplicate, but might still work.

**Comment by xzxADIxzx** [comment]
To install the mod, you need to unzip **all** files from the archive into a subfolder, read the installation instructions in the readme.

**Comment by xzxADIxzx** [comment]
I think you are dead

**Comment by kierkat10** [comment]
SORRY, I put the contents of the folder into a subfolder I named "Jaket" in UMM Mods and now it doesn't say there are any mods in the folder at all. Which is weird since I have about 30 mods in the folder. Then, I tried putting all of the other mods out and it worked! Thank you!

**Comment by coatlessali** [comment]
Pro Panda Tip: No mods being detected is generally a sign that you loaded the same mod twice.
