### ISSUE TITLE
Mod loading but not working on Linux

### ISSUE THREAD

**Issue by WORMSTweaker** [xzxADIxzx/Join-and-kill-em-together#11]
Hello! 

Probably a low concern issue, but I cannot seem to get the mod working under Linux
The mod loads correctly (it appears in the log, it is in the mod list, it can be enabled, everything appears fine) but none of the menus work
Just in case it was a default key issue, changing the default bound key does nothing too

Any ideas or directions to debug this further? Thanks in advance!

**Comment by xzxADIxzx** [comment]
* Are there any errors in the logs? If yes, please send it to me.
* You can't open any menus, but can you connect to a friend? I need to localize the problem.
* Are there any new keys in the control settings?
* Do you have other mods installed? Should only be BenInEx, UMM and Jaket.

**Comment by WORMSTweaker** [comment]
- No errors in the logs, some warnings but they don't seem related to Jaket, I can attach it if you really want me to
- For now, no, I haven't got someone on hand to try it out, in fact I expected issues and wanted to install the mod before I got a friend onboard
- Yes, there is the 3 new keys added by the mod
- I do, IntroSkip, UntraNixVideoFix. Just tried without said mods by completely uninstalling them, still the same issue

**Comment by xzxADIxzx** [comment]
To be honest, I have never been able to run ULTRAKILL on my Linux, so it will be difficult for me to understand what's going on...
* Send a screenshot of the directory with the mod installed.
* Do you know how to use the Unity Explorer mod? It would help a lot.

### Unity Explorer
1. You need to open explorer
2. Select the DontDestroyOnLoad scene
3. Find an object named Jaket
4. And send me a screenshot

**Comment by WORMSTweaker** [comment]
Okay so update on all that, and possibly means that the issue is probably going further than just Jaket

- Screenshot attached, mod folder, as you can see not much in there
![Screenshot_20230726_135201](https://github.com/xzxADIxzx/Join-and-kill-em-together/assets/1344245/78f26503-6b3c-4133-9eba-69ed3e5428b7)
- No, I don't, but I'll manage... That is if I could get into UE

The reason I'm saying this might be bigger than just Jaket, is that UE does load on the intro cutscene, but as soon as I get to the main menu, everything disappear, and the keybind for UE (F7) doesn't work...

So I'm thinking, that's a whole other issue

**Comment by xzxADIxzx** [comment]
How did you manage to get Jaket running with r2modman?!
How many people did not try for all, only manual installation worked ._.

**Comment by coatlessali** [comment]
> The reason I'm saying this might be bigger than just Jaket, is that UE does load on the intro cutscene, but as soon as I get to the main menu, everything disappear, and the keybind for UE (F7) doesn't work...

I've experienced this bug before. Keep the menu open when transitioning between loading screens. Hope it helps.

**Comment by WORMSTweaker** [comment]
> > The reason I'm saying this might be bigger than just Jaket, is that UE does load on the intro cutscene, but as soon as I get to the main menu, everything disappear, and the keybind for UE (F7) doesn't work...
> 
> I've experienced this bug before. Keep the menu open when transitioning between loading screens. Hope it helps.

Problem is, this doesn't work, even locking the UE windows doesn't work

**Comment by coatlessali** [comment]
Until I can get a VM set up to debug this more, here are some potential short term fixes:

- Avoid using r2modman, set up BepInEx/UMM with Proton. There are guides in the BepInEx documentation for this.
- Try different Proton versions.

Also you shouldn't need UltraNixVideoFix for Proton. That was made to work around a bug with the native Unity for Linux client.

**Comment by WORMSTweaker** [comment]
As stupid as it sound, starting up r2modman with `WINEDLLOVERRIDES="winhttp=n,b"` fixes the issue
I consider this a "*solution*", maybe not a great one, but one working enough for me

Closing this as I don't think it's needed to discuss it further

**Comment by coatlessali** [comment]
This is definitely the way to go. WINE/Proton don't automatically override DLLs by default.
