### ISSUE TITLE
white team

### ISSUE THREAD

**Issue by MyNameIsJoel123** [xzxADIxzx/Join-and-kill-em-together#111]
i have seen some users be white team, how do you obtain it?

**Comment by Glitch31415** [comment]
use our fork
https://discord.gg/pnXNRcnr
https://github.com/whyis2plus2/custom-jaket2

**Comment by xzxADIxzx** [comment]
DO NOT

**Comment by xzxADIxzx** [comment]
Custom jaket clients are not official, they are not supported by me, and they are not compitable with the official jaket release; but moreover, you can join to the lobbies that are made with an official jaket client, which will lead to desynchronization and a horrible experience for everyone

**Comment by xzxADIxzx** [comment]
And the last thing is... GOD DAMN, 5 TEAMS ARE ENOUGH

**Comment by Glitch31415** [comment]
bro absorbed all the salt from the oceans for that one

**Comment by MyNameIsJoel123** [comment]
cum team

**Comment by GithubBreen** [comment]
1984 strikes hard with this one

**Comment by MyNameIsJoel123** [comment]
i love men

**Comment by HaloDragon7410** [comment]
> i love men

Who asked

**Comment by MyNameIsJoel123** [comment]
ermm no one

**Comment by MyNameIsJoel123** [comment]
> **[Glitch31415](/Glitch31415) ** commented

i heard about an update, where can i find that??

**Comment by Glitch31415** [comment]
what do you mean? the github has moved to https://github.com/Glitch31415/modded-jaket2
here's an invite to the discord server, we can help more there https://github.com/Glitch31415/modded-jaket2
