### ISSUE TITLE
Trails lack shaders in OpenGL renderer

### ISSUE THREAD

**Issue by coatlessali** [xzxADIxzx/Join-and-kill-em-together#113]
When using the OpenGL renderer via `-force-glcore`, the trails behind players appear purple and do not have shaders.

![image](https://github.com/user-attachments/assets/187e7603-3047-47fb-9673-d5c62b853ae7)

**Comment by coatlessali** [comment]
You likely do not have OpenGL enabled as a rendering backend in your project settings. V2's trails are fine.

![image](https://github.com/user-attachments/assets/70e17fc6-5e6e-4341-a255-44d89e23c6ff)

**Comment by xzxADIxzx** [comment]
Wdym "OpenGL enabled" and what project do you mean?

**Comment by coatlessali** [comment]
Do you use Unity to generate your `jaket-assets.bundle` file?

**Comment by coatlessali** [comment]
Also, I made this image a long time ago for UKDS, but it should prove useful. 
![image](https://github.com/user-attachments/assets/24aa431a-a401-4d34-81c9-f7b4ccf52e9e)

**Comment by xzxADIxzx** [comment]
Yeah, I use Unity, but who cares? I don't build the game, and I use either Unity standard shaders that must be included in the game or ultrakill shaders, so it does not matter

**Comment by coatlessali** [comment]
Unity is not exporting your assetbundles with OpenGL support. If there is some other way of generating assetbundles I would like to know exactly what it is.

"Who cares" includes:
- People with older GPUs that don't support D3D11.
- People on MacOS/Linux that don't have access to Vulkan for D3D11 -> Vulkan translation, meaning they are stuck with OpenGL.

**Comment by xzxADIxzx** [comment]
I didn't mean the issue when said "who cares". I said that because there are no **shader assets** in the bundle, I use shaders from the game.

**Comment by coatlessali** [comment]
I believe any assets in the bundle, even if they use shaders from the game, will have those shaders compiled from an intermediary language to a per-renderer format, which by default is only D3D11. I have reason to believe that enabling OpenGL as a target in the Unity settings would fix this.

I could very well be wrong, but I think it's worth a shot.

**Comment by xzxADIxzx** [comment]
Okay I will try 2 build it with OpenGL enabled and then send you

**Comment by xzxADIxzx** [comment]
But I would also appreciate you telling me how to enable OpenGL on Windows, so that I will not have to download Ultrakill on my slow hard drive with Linux

**Comment by coatlessali** [comment]
The process is no different. If the assetbundle has OpenGL shaders embedded, it will work on all Platforms. A Linux version is not needed. Most people playing the game on MacOS/Linux will be playing the Windows version with a compatibility layer anyways.
https://docs.unity3d.com/2020.1/Documentation/Manual/OpenGLCoreDetails.html
This page explains it, but be sure to choose **both** OpenGLCore **and** Direct3D 11. Otherwise, you will end up with *only* OpenGL shaders.

**Comment by xzxADIxzx** [comment]
I mean, how do I force Ultrakill to use OpenGL, so that I will not have to wait for u to test my bundle

**Comment by coatlessali** [comment]
Simply put `-force-glcore` in your launch options in Steam.
A full list of arguments can be found here: https://docs.unity3d.com/2019.4/Documentation/Manual/PlayerCommandLineArguments.html

**Comment by xzxADIxzx** [comment]
Thanks, I'll test it as soon as my classes end (around 3 p.m. by MSK)

**Comment by xzxADIxzx** [comment]
Fixed
