### ISSUE TITLE
did everything correct, mod doesn't show.

### ISSUE THREAD

**Issue by ZappinZapper** [xzxADIxzx/Join-and-kill-em-together#13]
i extracted every file, tried subfolder after subfolder, pissed myself, screamed, cried, attempted suicide and all i see is this.

![image](https://github.com/xzxADIxzx/Join-and-kill-em-together/assets/106945906/06499dd0-e7ac-4e7d-81c4-885ade590a41)

![image](https://github.com/xzxADIxzx/Join-and-kill-em-together/assets/106945906/3298f8b1-e4dc-468f-ae62-b378258ffbd4)

**Comment by coatlessali** [comment]
The downloads are under the releases page, not the "code" button.

Also the only file you need is Jaket.dll in the UMM mods folder for it to function.

**Comment by ZappinZapper** [comment]
fuck

**Comment by ZappinZapper** [comment]
fuck

**Comment by ZappinZapper** [comment]
wait shit where is that

**Comment by coatlessali** [comment]
https://github.com/xzxADIxzx/Join-and-kill-em-together/tags

**Comment by ZappinZapper** [comment]
thx

**Comment by xzxADIxzx** [comment]
Ahahahahahaha
