### ISSUE TITLE
Lan support?

### ISSUE THREAD

**Issue by BloodLetters** [xzxADIxzx/Join-and-kill-em-together#21]
is jaket will support lan in future?

**Comment by Luigifan2019** [comment]
who needs lan when you can just simply friend the person on steam and send them a request to play with them

**Comment by GithubBreen** [comment]
lan best

**Comment by xzxADIxzx** [comment]
No, but I'll add public lobbies, so u can connect without sending friend code.

**Comment by BloodLetters** [comment]
> No, but I'll add public lobbies, so u can connect without sending friend code.

ohh. ok

**Comment by xzxADIxzx** [comment]
I've added public lobbies so I don't see any reason to add LAN support

**Comment by sidoka-contact** [comment]
wouldn't lan support allow people to play together without internet connection? (like, the actual intended use for lan)

**Comment by PyroGabrielKotzell** [comment]
it would require both players to be on the same device, and i don't think adi want's to create an input splitter

**Comment by xzxADIxzx** [comment]
I think everyone have an Internet connection so LAN becomes useless in 2k23
