### ISSUE TITLE
lobby doesnt create

### ISSUE THREAD

**Issue by Danilmikhan** [xzxADIxzx/Join-and-kill-em-together#29]
ok so can you fix that when your ultrakill is pirate(i will get the real one soon i hope as a christmas gift) it doesnt create a lobby, i dont know why but my friend thinks that its a steam api problem

**Comment by PyroGabrielKotzell** [comment]
crack version of ultrakill are not compatible with the paid ones, that's because the crack version tries to use the steam api which it obviously can't, as such you and your friend should use goldberg to emulate steam and have a vpn or some software to trick the connection into a lan one such as Hamachi, radmi and parsec.

**Comment by Danilmikhan** [comment]
my pirated copy uses goldberg

**Comment by PyroGabrielKotzell** [comment]
and his?

**Comment by Danilmikhan** [comment]
idk let me ask him

**Comment by Danilmikhan** [comment]
this will take a while

**Comment by PyroGabrielKotzell** [comment]
i can wait

**Comment by Danilmikhan** [comment]
also i kinda deleted the goldberg thing recently but i can download it again

**Comment by Danilmikhan** [comment]
cuz i wanted for steam to think im launching the actual game for the funny

**Comment by PyroGabrielKotzell** [comment]
🤦‍♂️

**Comment by Danilmikhan** [comment]
do i need to tho?

**Comment by PyroGabrielKotzell** [comment]
goldberg? YES

**Comment by PyroGabrielKotzell** [comment]
both you and your friend

**Comment by Danilmikhan** [comment]
ok

**Comment by Danilmikhan** [comment]
i dont think hes online

**Comment by PyroGabrielKotzell** [comment]
wdym?

**Comment by Danilmikhan** [comment]
also with the goldberg thing extracted jaket didnt work

**Comment by Danilmikhan** [comment]
i meant he is afk

**Comment by Danilmikhan** [comment]
even though he is on do not disturb he answers quickly

**Comment by PyroGabrielKotzell** [comment]
please come to discord

**Comment by PyroGabrielKotzell** [comment]
we would be better there

**Comment by Danilmikhan** [comment]
k

**Comment by Danilmikhan** [comment]
i cant find you

**Comment by PyroGabrielKotzell** [comment]
Spookymaster from jaket ds

**Comment by xzxADIxzx** [comment]
You downloaded a pirated version of the game and ask **ME** for the **HELP**?
# JUDGMENT
