### ISSUE TITLE
how 2 download?! (real)

### ISSUE THREAD

**Issue by osilol11** [xzxADIxzx/Join-and-kill-em-together#3]
so its actually cool that you created multikill another version, but how do i download it in ultrakill? is it requires BepInEx or UMM?

**Comment by xzxADIxzx** [comment]
It requires BepInEx & UMM.
The mod is not completely ready yet, so the only way to install it is to download the repository and compile it locally.
Cheers

**Comment by xzxADIxzx** [comment]
If you're still interested, tomorrow I'll do a prerelease on Thunderstore

**Comment by osilol11** [comment]
That would be cool, but its your own decision to pre release it or not.

**Comment by ninoo32** [comment]
> It requires BepInEx & UMM. The mod is not completely ready yet, so the only way to install it is to download the repository and compile it locally. Cheers

Yeah, would be nice if you pre release it

**Comment by ninoo32** [comment]
> If you're still interested, tomorrow I'll do a prerelease on Thunderstore

Yeah, would be really nice if you pre release it

**Comment by xzxADIxzx** [comment]
Right now I have a more or less stable version, I'll test it a little more and send it to the pre-release

**Comment by osilol11** [comment]
Yay!!!

**Comment by xzxADIxzx** [comment]
Well, I tested a little and I won’t refuse my words - I’ll pre-release the mod, but it’s still very raw.
Be careful and if something goes wrong, just re-enter the lobby.

**Comment by osilol11** [comment]
Okay! thanks for pre-releasing the mod!!
