### ISSUE TITLE
I'm gonna buy the game soon and...

### ISSUE THREAD

**Issue by ERENPROO** [xzxADIxzx/Join-and-kill-em-together#30]
And I wanna ask things.
1-Can you customize your color like the RGB slider at the weapon color?
2-Can you edit the label of V1 (I'mma do mine V1.665)
3-If I use a cheat table that uses Cheat Engine (I won't, just curiosity.), will it break the mod/game?

If first 2 aren't at the mod, it would be cool if you add them. 3rd one was just my *swordsmachine hp halved noise* being curious.

**Comment by xzxADIxzx** [comment]
1. No, but I will add cosmetic decorations someday
2. In multiplayer you always play as V3, I even explained it in the lore
3. ~~Why do you need a cheat engine?!~~ Most likely yes, it will break everything to hell

I’m unlikely to add the first two, or rather no, I definitely won’t add them in the form in which you present them.
Cheers~ ❤️

**Comment by ERENPROO** [comment]
Where is the lore though.

**Comment by xzxADIxzx** [comment]
Bestiary
