### ISSUE TITLE
Can you enter CyberGrind with your friend?

### ISSUE THREAD

**Issue by ERENPROO** [xzxADIxzx/Join-and-kill-em-together#31]
As mentioned above, can I CyberGrind with my friend?

**Comment by xzxADIxzx** [comment]
Yup, you are able to enter CB, but it won't work properly **,_,**

Wait for 1.1.0 update,
Cheers~ ❤️

**Comment by ERENPROO** [comment]
BTW, I can't see cat ears for a reason. Is it auto-enabled upon choosing pink (UwU label really shows itself.)?

**Comment by xzxADIxzx** [comment]
Yup, cat ears are only visible when you are in the pink team
