### ISSUE TITLE
Mod isn't working

### ISSUE THREAD

**Issue by Naimer457** [xzxADIxzx/Join-and-kill-em-together#32]
I did all the steps i found in a video, and when pressing F1 in sandbox didn't appear any invite thing

**Comment by xzxADIxzx** [comment]
* Version of the mod?
* Link to the video?
* BepInEx version?
* UMM version?
* Manual or r2mm?
* Licensed or cracked game?

**Comment by Naimer457** [comment]
Nevermind, i tried the version from thunderstore and now it works thx anyway

**Comment by xzxADIxzx** [comment]
Okay, goodnight
