### ISSUE TITLE
2 bugs I found

### ISSUE THREAD

**Issue by ERENPROO** [xzxADIxzx/Join-and-kill-em-together#34]
1- V1 isn't in the bestiary.
2-For some reason, I can't whiplash Drones to me (I wasn't the lobby owner.).

**Comment by ERENPROO** [comment]
![Screenshot_20231117_205337_GitHub.jpg](https://github.com/xzxADIxzx/Join-and-kill-em-together/assets/89633652/4bccc482-868d-4eb9-8339-f592bf5b3c03)

Then, I think I got this one wrong.

**Comment by ERENPROO** [comment]
What's that extra question mark in the bestiary?

**Comment by xzxADIxzx** [comment]
Extra question mark?

**Comment by ERENPROO** [comment]
Yes, even if I completed the whole game...

**Comment by xzxADIxzx** [comment]
Ugh, idk, V3 is Filth from the point of code's view so it must be unlocked from the very beginning

**Comment by ERENPROO** [comment]
Nvm, I cheated my way thru 0-S, so I didn't see Something Wicked.
