### ISSUE TITLE
This is just me being stupid

### ISSUE THREAD

**Issue by Stoniac** [xzxADIxzx/Join-and-kill-em-together#42]
But I think it would be nice if you couldn't rebind settings to Mouse0

**Comment by xzxADIxzx** [comment]
Uh, well, maybe, idk

**Comment by Stoniac** [comment]
It would be very appreciated given that as of right now every time I left click it opens the settings menu lmao
If you don't feel like doing that or don't get around to it, do you know any fixes I could do? I've cleared the game cache uninstalled reinstalled deleted my entire ultrakill mod folder and it's still bound to mouse0.

**Comment by zUltimaPG3D** [comment]
check LocalPrefs.json (i think, not 100% sure about it) in Preferences folder

**Comment by Stoniac** [comment]
Not in there. Found four LocalPrefs.json files on my entire PC, none of them related.

**Comment by zUltimaPG3D** [comment]
well i mean, i'd say check json files in the Preferences folder of your ultrakill install and see if any jaket related entry is there

**Comment by PyroGabrielKotzell** [comment]
Not LocalPrefs.json but preferences.json that is located in a subfolder of your ultrakill folder.
preferences.json is saved also in steam cloud, meaning uninstalling and reinstalling won't clear it

Look in it and delete every jaket.bind line you find, also, consider joining the discord

**Comment by Stoniac** [comment]
Could I get a Discord link?

**Comment by Stoniac** [comment]
Also, I'm using R2ModMan, so the files aren't in the same places.

**Comment by PyroGabrielKotzell** [comment]
In readme, or thunderstore page (which shows the readme)

**Comment by PyroGabrielKotzell** [comment]
R2modman doesn't change the location, ultrakill folder>preferences(i think)>preferences.json

**Comment by zUltimaPG3D** [comment]
> Also, I'm using R2ModMan, so the files aren't in the same places.

Prefs.json is part of ultrakill, not the mod

**Comment by Stoniac** [comment]
Opened prefs.json - there were jaket related settings but no keybinds.

**Comment by PyroGabrielKotzell** [comment]
Then add one jaket.bind for the keybinds menu, i cannot give you one as i am on my pc and i don't remember how it was written exactly

**Comment by Stoniac** [comment]
I'm not sure how to do that.

**Comment by xzxADIxzx** [comment]
So yeah, delete all lines that starts with "jaket.bind" from *ULTRAKILL*/Preferences/Prefs.json
Also I'll add a keybind (shift+alt+del, idk) for clearing all the settings, just wait

**Comment by PyroGabrielKotzell** [comment]
> I'm not sure how to do that

You just edit the json and write a line with 
jaket.bindF3='959'
(obviously not this exactly) i don't remember what the bind was actually named and to which numer you would need to put it to make it f3...
But if you find what the bind is named you can edit the ultrakill in-game options and put something to f3 to see which number f3 corresponds to to change the jaket bind to that.

**Comment by xzxADIxzx** [comment]
You don't have to recall the name of the keybind just remove it - the mod will use the default value

**Comment by Stoniac** [comment]
Worked perfectly, thank you so much for the help
