### ISSUE TITLE
Can't go to second page of emotes

### ISSUE THREAD

**Issue by T1KK** [xzxADIxzx/Join-and-kill-em-together#43]
I don't know if it's something wrong with my game, but i literally can't go to the second page of the emotes. I've tried waiting with my mouse over it, clicking, arrow keys, it just doesn't go to the next page. How do i go to the next page of emotes?

**Comment by PyroGabrielKotzell** [comment]
It should just work by getting the selector on the bottom and waiting

**Comment by xzxADIxzx** [comment]
It must work, just move your mouse down and wait a little bit (1 sec if I recall correctly)

**Comment by xzxADIxzx** [comment]
The only case in which it may not work is if your bundle is damaged. Try reinstalling the mod and restarting your computer.

**Comment by T1KK** [comment]
i've tried that and i've tried waiting, it just won't let me go to the second page no matter how long i hover over it.

**Comment by T1KK** [comment]
figured out the cause, apparently BetterWeaponWheel interferes with the emote wheel
