### ISSUE TITLE
Wiplash related bug

### ISSUE THREAD

**Issue by ERENPROO** [xzxADIxzx/Join-and-kill-em-together#44]
If I try to whiplash the enemies that is normally pulled torwards you, you get pulled torwards them. I was trying to instakill Schisms by splaytting them into ground and plan just gets ruined.
This happens if you are not the owner of the lobby though.

**Comment by xzxADIxzx** [comment]
I know, most likely it will be fixed in 1.1.0 if I don't forget.

**Comment by ERENPROO** [comment]
> I know, most likely it will be fixed in 1.1.0 if I don't forget.

Okay, good luck doing the 1.1.0 update now then.
