### ISSUE TITLE
Wont work.

### ISSUE THREAD

**Issue by Alistair8** [xzxADIxzx/Join-and-kill-em-together#59]
The mod setup and stuff worked and the mod seems to be working, but the public lobbies are completely blank and joining a friend by  code doesnt work. (Im not using the steam copy if that makes a difference)

**Comment by PyroGabrielKotzell** [comment]
yes that makes a difference, the mod uses steam lobbies, join the server and look at the faq for more info about non-steam copies of ultrakill

**Comment by PyroGabrielKotzell** [comment]
we won't help tho :)

**Comment by xzxADIxzx** [comment]
Buy game / read guide in the discord server of the mod
