### ISSUE TITLE
Main weapons dissapearing when typing and pressing L, in a lobby, only in P-1/P-2

### ISSUE THREAD

**Issue by 948347893875338** [xzxADIxzx/Join-and-kill-em-together#64]
Everytime i go into P-1/P-2 with my friend, and i type something like "lol", it brings up the tele menu (cuz i like cheats on), i finish typing, press enter, get out of the menu, all weapons from slot 1 to slot 6 are gone. Only my UFG weapons are there.
wtf is happening????? https://youtu.be/Gt02qfQL7H8

**Comment by kekson1a** [comment]
you have bound teleport menu to L, this is not in any way related to jaket, the teleport menu hides your hands
![Screenshot](https://github.com/xzxADIxzx/Join-and-kill-em-together/assets/126417868/622cfe94-31c9-4306-8c14-571a5536760c)

**Comment by 948347893875338** [comment]
https://youtu.be/Gt02qfQL7H8
maybe take a look at the video????
(yes i realised im an idiot, i used githubs link feature)

**Comment by kekson1a** [comment]
>  maybe take a look at the video???? 
i have looked at the video, you typed "lol" and this triggered your teleport menu keybind

**Comment by kekson1a** [comment]
> > maybe take a look at the video????
i have looked at the video, you typed "lol" and this triggered your teleport menu keybind

**Comment by 948347893875338** [comment]
yes it did
and i close out of the teleport menu
the weapons are gone
https://www.youtube.com/watch?v=LQKe6S97-cM
another video of *phone recording* of they are gone

**Comment by xzxADIxzx** [comment]
UFG? Are you using other mods with Jaket?!?!

**Comment by kekson1a** [comment]
> UFG? Are you using other mods with Jaket?!?!

i just wanted to say this, this bug doesn't even happen to me, might be an issue of using UFG with Jaket

**Comment by 948347893875338** [comment]
im just wondering wtf was messing up the keybinds to do that
![image](https://github.com/xzxADIxzx/Join-and-kill-em-together/assets/121643321/08a0a927-1bb3-406d-9a71-0380d0b8c517)
