### ISSUE TITLE
jaket doesnt start

### ISSUE THREAD

**Issue by Signus12** [xzxADIxzx/Join-and-kill-em-together#65]
dont really know what the issue is did everything the guide on discord told me to do if it helps this is the error in the bepinex console [Error  : Unity Log] TypeLoadException: Could not load type of field 'Jaket.Log:Logger' (3) due to: Could not resolve type with token 0100001f (from typeref, class/assembly plog.Logger, plog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:plog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:plog.Logger member:(null) signature:<none>
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.InputSystem.InputSystem:.cctor()

**Comment by xzxADIxzx** [comment]
Do you have a licensed game from Steam?
Seems like there is a missing dependency... plog was added to ULTRAKILL in the violence update, so I think you have an old version of the game.
Also, it would be easier if you pinged me in Discord :3

**Comment by Signus12** [comment]
> Do you have a licensed game from Steam? Seems like there is a missing dependency... plog was added to ULTRAKILL in the violence update, so I think you have an old version of the game. Also, it would be easier if you pinged me in Discord :3

I'll update and check back later thanks

**Comment by xzxADIxzx** [comment]
Okay, I hope he figured it out...
