### ISSUE TITLE
Join with ip

### ISSUE THREAD

**Issue by Soleil-des-chats** [xzxADIxzx/Join-and-kill-em-together#67]
Can you add a way to make you can join without steam like with a ip ?

**Comment by PyroGabrielKotzell** [comment]
Hahaha no
It would be much more complicated and a security issue
Just use goldberg

**Comment by Theoyeah** [comment]
Why, if you have a genuine copy just use steam, there no reason to not use steam. And if ur craked, use goldberg just like the other dude said and its also a very risky thing to spread your ip, you can get in trouble.

**Comment by xzxADIxzx** [comment]
Check #faq in our discord server if you have a cracked version of the game; otherwise use Steam and private lobbies.

**Comment by kierkat10** [comment]
> Why, if you have a genuine copy just use steam, there no reason to not use steam. And if ur craked, use goldberg just like the other dude said and its also a very risky thing to spread your ip, you can get in trouble.

The fact that some people still think having your IP is "risky" is so funny

**Comment by PyroGabrielKotzell** [comment]
> The fact that some people still think having your IP is "risky" is so funny

Well, it depends.
Having an IP gives you the general location where the packets are being sent from. 
But there is another security issue, which happens more frequently.
You actually have to open ports on your devices for packets to transmit over via internet, and those ports are a welcoming mat for hackers.
By having your ip, they can scan all open ports on your connection and if they find a breach they get in.
This wouldn't be a problem if the only ports open were the game's ones, but you never know which devices have some open that are completely unchecked/unsafe.

Obviously I don't think you'd find an hacker like this on ultrakill using a multiplayer mod. But you never know.
