### ISSUE TITLE
List of bugs ive found too

### ISSUE THREAD

**Issue by osilol11** [xzxADIxzx/Join-and-kill-em-together#7]
Player Standing: Sometimes Host Just Stops and stand in one place. (Maybe caused by pausing game, possibly not)

Invisible Rockets: Rockets Are Not Visible For Client

Cybergrind Broken: For Some Users, There's only random spawns. Yesterday, my friend encountered a bunch of virtue (instead of filths), some other clients encountored Corpse Of Minos on first wave.

Doors Closed: Some level contains doors that wont open even after killing each enemy.

Secret Levels Multiplayer Are Not Working: We tried 0-S And we couldn't find each other (we was meeting at beggining) We was still in a lobby, i pressed Z and there was no location of Host.

Prime Levels: I think, it spawns wrong enemies for client. Client sees Corpse Of Minos healthbar and dont see anyone expect Host. Also There's no exit after beating minos prime (for client only)

Boss Levels: V2 (GREED). Client can't exit the V2 Room after First Phase. Corpse Of The Minos: Client can't see him. After beating him client doesnt see any exit.

Enemies Targets only host (Does that even count as a bug?): Self Explanatory.

That's all!

**Comment by xzxADIxzx** [comment]
Thank you for your efforts :3

**Comment by xzxADIxzx** [comment]
Doors, secret levels, prime levels and bosses are fixed; update the mod.

**Comment by xzxADIxzx** [comment]
Everything are fixed except The Cyber Grind, 5-S and the last one, but they are unimplemented features, not bugs.

Cheers~ ❤️
