### ISSUE TITLE
Downloading newest version of Jaket using R2modman does not create the .bundle folder

### ISSUE THREAD

**Issue by Theoyeah** [xzxADIxzx/Join-and-kill-em-together#82]
I tried downloading the newest version of Jaket using R2modman but i saw that it does not create the .bundle folder. It seems to happen to everyone and causes the "Oh no" to replace all text since Jaket cannot find the .properties files

**Comment by PyroGabrielKotzell** [comment]
apperantly the whole bundles folder gets extracted:
![image](https://github.com/xzxADIxzx/Join-and-kill-em-together/assets/116422802/124b1842-1e3d-473d-95cf-c7cf5967c52b)
can be fixed by manually creating a "bundles" folder with THIS name and putting all the .proprieties in there
