### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by Dal1ster** [xzxADIxzx/Join-and-kill-em-together#9]
this is a general question and if there is another place for me to put this is please let me know so that i can move it. My question is how do i create a lobby/invite players since nothing tells me how to do it or if it can do it. The mod is enabled in game and all the requirements are installed as well.

**Comment by xzxADIxzx** [comment]
You can always ask about this in our discord server, the link to which is at the end of the readme, but I’ll duplicate it anyway: you need to go into the game and press f1, then "Create Lobby" and "Invite Friend".
