### ISSUE TITLE
Doors not working for anyone except the main host

### ISSUE THREAD

**Issue by SsjGabe360** [xzxADIxzx/Join-and-kill-em-together#94]
My friend and I were playing with the Jaket mod and realized that the person who joins the lobby can't go through doors that open and are permanently locked inside of the room.

**Comment by FallenXin** [comment]
I also am stuck with that issue with my friends.

**Comment by PyroGabrielKotzell** [comment]
We know and have already fixed this issue.
please wait for a mod update.
